name: quantum-boolean
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - qiskit=1.2
  - numpy
  - scipy
  - sympy
  - gmpy2  # Important for symbolic computation performance
  - pip
  - python-symengine  # Accelerates sympy
  # Development tools (optional but recommended)
  - black
  - pylint
  - pytest
  - jupyter
